#!/bin/bash

# make sure GOPATH and GOPATH/bin is set for
# starport and packr2 commands be available to the host.
if [ -z "$GOPATH" ]
then
    export GOPATH=$HOME/go
fi
export PATH=$PATH:$GOPATH/bin
mkdir -p $GOPATH

# build the dependencies..
echo "building the ui..."
rm -rf starport/ui/dist
(cd starport/ui && \
    npm i >/dev/null && \
    npm run build >/dev/null)

echo "packing the ui..."
go get -u github.com/gobuffalo/packr/v2/packr2 >/dev/null
(cd ./starport/interface/cli/starport && \
    packr2)

# install Starport.
echo  installing starport...
go install -mod=readonly ./... 1>/dev/null

echo done!
